---
title: "Pooled National Coverage --- Countdown Analysis"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cerulean
    highlight: kate
  word_document:
    toc: false
    reference_docx: report-template.docx
  pdf_document:
    toc: false
    latex_engine: lualatex
params:
  cache: NULL
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  include = TRUE,
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  error = TRUE,
  fig.width=7, 
  fig.height=5, 
  dpi=1200
)

library(cd2030.pooled)
library(dplyr)

cache <- params$cache
national_estimates <- cache$national_estimates
```

## Overall National Coverage Estimates

### Measles 1 Coverage

```{r}
coverage_data <- process_coverage_data(.data = national_estimates, indicator = 'cov_measles1_penta1')
plot(coverage_data)
```

#### ðŸ“ Notes 

::: {custom-style="Style1"}

---

```{r, results='asis'}
print_notes(cache, 'national_coverage', 'Measles 1')
```

---

:::

### Penta 3 Vaccination Coverage

```{r}
coverage_data <- process_coverage_data(.data = national_estimates, indicator = 'cov_penta3_penta1')
plot(coverage_data)
```

#### ðŸ“ Notes 

::: {custom-style="Style1"}

---

```{r, results='asis'}
print_notes(cache, 'national_coverage', 'Penta 3')
```

---

:::

### BCG Coverage

```{r}
coverage_data <- process_coverage_data(.data = national_estimates, indicator = 'cov_bcg_penta1')
plot(coverage_data)
```

#### ðŸ“ Notes 

::: {custom-style="Style1"}

---

```{r, results='asis'}
print_notes(cache, 'national_coverage', 'BCG')
```

---

:::

### Rota 2 Coverage

```{r}
coverage_data <- process_coverage_data(.data = national_estimates, indicator = 'cov_rota2_penta1')
plot(coverage_data)
```

#### ðŸ“ Notes 

::: {custom-style="Style1"}

---

```{r, results='asis'}
print_notes(cache, 'national_coverage', 'Rota 2')
```

---

:::

### Measles 2 Coverage

```{r}
coverage_data <- process_coverage_data(.data = national_estimates, indicator = 'cov_measles2_penta1')
plot(coverage_data)
```

#### ðŸ“ Notes 

::: {custom-style="Style1"}

---

```{r, results='asis'}
print_notes(cache, 'national_coverage', 'Measles 2')
```

---

:::
